"""fixing zip in address and user

Revision ID: 7dcd900fa5e5
Revises: dec754e12065
Create Date: 2022-08-28 20:44:29.518877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dcd900fa5e5'
down_revision = 'dec754e12065'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
