"""fixing zip in address

Revision ID: dec754e12065
Revises: 7959b9535325
Create Date: 2022-08-28 19:51:03.040425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec754e12065'
down_revision = '7959b9535325'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('addresses_zip_key', 'addresses', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('addresses_zip_key', 'addresses', ['zip'])
    # ### end Alembic commands ###
